language: php
php: 7.1
dist: trusty

env:
  global:
    - BUILD_DIR=$TRAVIS_BUILD_DIR


before_install:
  - echo 'Started'
  - chmod +x ${BUILD_DIR}/build.sh

install:
  - echo 'Finished'

script: ${BUILD_DIR}/build.sh

jobs:
  include:
    - stage: Test
      if: (branch IN (master, develop, travis-refactor)) AND (type IN (pull_request))
