language: php
php: 7.1
dist: trusty

env:
  global:
    - BUILD_DIR=$TRAVIS_BUILD_DIR

jobs:
  include:
    - stage: Test
      if: (branch IN (master, develop)) AND (type IN (pull_request))
      before_install:
        - echo 'Started'
        - chmod +x $BUILD_DIR/build.sh
      before_script:
        - composer install
      script:
        - ls -d $HOME/.?*
        - ls $HOME
        - ls $HOME/bin
        - ls -d $BUILD_DIR/.?*
        - ls $BUILD_DIR
        - phpcs -i
        - $BUILD_DIR/build.sh
