language: php
php: 7.1
dist: trusty

env:
  global:
    - BUILD_DIR=$TRAVIS_BUILD_DIR

jobs:
  include:
    - stage: Test
      if: (branch IN (master, develop)) AND (type IN (pull_request))
      before_install:
        - echo 'Started'
        - chmod +x $BUILD_DIR/build.sh
      before_script:
        - composer global install
      script:
        - export PATH="$PATH:$HOME/.composer/vendor/bin"
        - phpcs -i
        - $BUILD_DIR/build.sh
