language: php
php: 7.1
dist: trusty

env:
  global:
    - BUILD_DIR=$TRAVIS_BUILD_DIR

jobs:
  include:
    - stage: Test
      if: (branch IN (master, develop)) AND (type IN (pull_request))
      before_install:
        - echo 'Started checking PR'
      before_script:
        - composer install
      script:
        - export PATH="$BUILD_DIR/vendor/bin:$PATH"
        - phpcs --config-set installed_paths $BUILD_DIR/vendor/drupal/coder/coder_sniffer
        - phpcs --standard=Drupal --extensions=php,module,inc,install,test,profile,theme,css,info,txt,md --ignore=node_modules,bower_components,vendor $BUILD_DIR
