language: php
php: 7.1
dist: trusty

before_install:
  - echo 'Started'

install:
  - echo 'Finished'

jobs:
  include:
    - stage: Test
      if: (branch IN (master, develop, travis-refactor)) AND (type IN (pull_request))
