version: 2
jobs:
  build:
    docker:
      - image: circleci/php:latest
    working_directory: ./
    steps:
      - checkout:
          path: ./
      - run:
          name: "Install Dependencies"
          command: |
            composer install
