version: 2
jobs:
  build:
    docker:
      - image: circleci/php:latest
    steps:
      - checkout
      - run:
          name: "Install dependencies"
          command: composer install
      - run:
          name: "Set Drupal coding standards"
          command: vendor/bin/phpcs --config-set installed_paths vendor/drupal/coder/coder_sniffer
      - run:
          name: "Test phpcs"
          command: vendor/bin/phpcs -i


#      - run: phpcs --config-set installed_paths vendor/drupal/coder/coder_sniffer
#      - run: phpcs --standard=Drupal --extensions=php,module,inc,install,test,profile,theme,css,info,txt,md --ignore=node_modules,bower_components,vendor $BUILD_DIR
