version: 2
jobs:
  build:
    docker:
      - image: circleci/php:latest
    steps:
      - checkout
      - run:
          name: "Install Dependencies"
          command: composer install
      - run: export PATH="$BUILD_DIR/vendor/bin:$PATH"
      - run: phpcs --config-set installed_paths $BUILD_DIR/vendor/drupal/coder/coder_sniffer
      - run: phpcs --standard=Drupal --extensions=php,module,inc,install,test,profile,theme,css,info,txt,md --ignore=node_modules,bower_components,vendor $BUILD_DIR
